### ISSUE TITLE
The file is corrupt, or compression was misconfigured? 

### ISSUE THREAD

**Issue by Sotatek-TrungHoang** [crispcat/UnityEthereumClient#1]
WebGL show error: "Unable to parse Build/BuildTest.framework.js! The file is corrupt, or compression was misconfigured? (check Content-Encoding HTTP Response Header on web server)". Please help me!!!

**Comment by crispcat** [comment]
You need to disable compression for your WebGL build.
https://docs.unity3d.com/Manual/webgl-deploying.html
